name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Container Image
        working-directory: ./naming-service
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API gateway Container Image
        working-directory: ./API-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Book Service Container Image
        working-directory: ./book-service
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build ExchangeService Container Image
        working-directory: ./exchange-rate-service
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build
        
      - name: Push to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-service:latest ${{ secrets.DOCKER_USERNAME }}/naming-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:latest ${{ secrets.DOCKER_USERNAME }}/book-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/exchange-service:latest ${{ secrets.DOCKER_USERNAME }}/exchange-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/exchange-service:${{github.run_id}}


