name: Continuous Integration with Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
	
    # Sem essa action o seu código não é baixado pro ambiente de build
    steps:
      - uses: actions/checkout@v2
	  
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
 
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
         java-version: '16'
         distribution: 'adopt'
      - name: Build Eureka Server Container Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests

