name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Container Image
        working-directory: ./naming-service
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API gateway Container Image
        working-directory: ./API-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Book Service Container Image
        working-directory: ./book-service
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build ExchangeService Container Image
        working-directory: ./exchange-rate-service
        run: mvn spring-boot:build-image -DskipTests

